

version: '3.3'

services:
  api:
    build:
      context: PhotoMemory/.
      args:
        SERVER_PORT: 8000
        MARIADB_PORT: 3306
        MARIADB_IP: db
        MARIADB_USERNAME: MARIADB_USER
        MARIADB_PASSWORD: MARIADB_PASS
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: MARIADB_ROOTPASS
      MYSQL_USER: MARIADB_USER
      MYSQL_PASSWORD: MARIADB_PASS
      MYSQL_DATABASE: pruebas
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped


