FROM openjdk:17
ARG JAR_FILE=build/libs/*.jar
ARG SERVER_PORT
ARG MARIADB_PORT
ARG MARIADB_IP
ARG MARIADB_USERNAME
ARG MARIADB_PASSWORD
ARG MARIADB_DATABASE

ENV SERVER_PORT=${SERVER_PORT}
ENV MARIADB_PORT=${MARIADB_PORT}
ENV MARIADB_IP=${MARIADB_IP}
ENV MARIADB_USERNAME=${MARIADB_USERNAME}
ENV MARIADB_PASSWORD=${MARIADB_PASSWORD}
ENV MARIADB_DATABASE=${MARIADB_DATABASE}

COPY ${JAR_FILE} app.jar
EXPOSE 8000

ENTRYPOINT ["java","-jar","/app.jar"]